### PR TITLE
[NOSQUASH] Resync Apache

### PR DESCRIPTION
**Pull request by ash211**
Conflicts caused by introduction of a new Flume profile at 0c03297bf0e87944f9fe0535fdae5518228e3e29

### CODE REVIEW

**Comment by ash211** [comment]
@robert3005 @onursatici @mccheah -- flume is going away upstream, see the linked commit.  Should we remove it now in Palantir Spark or keep it until it's actually deleted?  Question is whether to enable the new flume profile or not

**Comment by robert3005** [comment]
I wouldn't. Just roll with upstream. Also can't wait for removal of hive.

**Comment by ash211** [comment]
Upstream created the profile and enabled it by default, so we will too

+1 on being able to remove Hive!

**Comment by robert3005** [comment]
Ah, then remove it. Flume is flaky

**Comment by ash211** [comment]
force pushed without the last commit, but looks like circle kicked off a repeat build of the previous commit

flume profile **not** added to:
- mvn install
- sbt externalDependencyClasspath
- dev/publish.sh
  - mvn deploy

**Pull request merged**
