### PR TITLE
Re-enable tests

### PR DESCRIPTION
**Pull request by ash211**

### CODE REVIEW

**Comment by pwoody** [comment]
dependency:go-offline doesn't run tests. Also we should probably put the test section in the test block.

Probably need to just redo most of the circle.yml. Maven is really slow compared to SBT unless we are doing something horribly wrong (~50 min v.s. ~20 min for builds).

**Comment by ash211** [comment]
For reference the amplab jenkins build takes about 2hr to run a verify build: https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/lastSuccessfulBuild/

**Comment by ash211** [comment]
So this times out after a single command exceeds 120min -- a [Circle limit](https://discuss.circleci.com/t/timeout-more-than-120-minutes/640)

Timing of a full test run on my laptop:
- RAT checks: 2 seconds
- Scala style checks: 30 seconds
- Python style checks: 34 seconds
- R style checks: (skipped)
- build tests: 48 seconds
- building Spark: 9min9sec
- detecting binary incompatibilities with MiMa: 1min54sec
- running Spark unit tests: XminYsec clock time
 - Spark unit tests are run with 4 threads in parallel so below times are modules and their per-thread time (not wall clock time), assuming I reading these correctly
 - core: 10min47sec
 - external/kafka-0-10: 11min22sec
 - external/flume: 12min
 - mesos: 12min3sec
 - yarn: 17min24sec
 - external/kafka-0-8: 17min40sec
 - graphx: 18min13sec
 - streaming: 21min55sec
 - external/kinesis-asl: 21min59sec
 - sql/catalyst: 26min47sec
 - repl: 28min5sec
 - mllib: 36min40sec

**Comment by ash211** [comment]
I think the approach we should take for running tests in circle is to parallelize the Spark unit tests into separate circle containers and provide a list of modules (mesos, yarn, graphx, etc) that are run on each container.

**Comment by ash211** [comment]
Replaced with https://github.com/palantir/spark/pull/78

**Pull request closed without merging**
