### PR TITLE
Fix publish

### PR DESCRIPTION
**Pull request by robert3005**
@mccheah this fixes #424

### CODE REVIEW

**Comment by mccheah** [comment]
Except `bintrayUpload` is still `SKIPPED` here? https://circleci.com/gh/palantir/spark/7298?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by robert3005** [comment]
it's because of https://github.com/palantir/spark/blob/master/gradle/publish.gradle#L45

**Comment by mccheah** [comment]
I thought that was supposed to be done, e.g. in conjure-java-runtime https://github.com/palantir/conjure-java-runtime/blob/develop/gradle/publish-jar.gradle#L29

**Comment by robert3005** [comment]
anything that's not a tagged commit will always return false for that check

**Comment by mccheah** [comment]
Ah I thought that this only returned false if the repository was in a dirty state, e.g. untracked files. We should probably remove the onlyIf clause because we want to be publishing snapshots also.

**Pull request merged**
