### PR TITLE
Fix for ineligible filters, use compressed block size

### PR DESCRIPTION
**Pull request by pwoody**
@schlosna @robert3005 @lynchmattj

Fixes two important bugs:
1. if you have a filter that cannot translate to a parquet filter this would previously fail.
2. properly generate splits from the compressed size. totalByteSize is the size after decompression, so it would previously bleed the split into the next block causing duplicate data.

### CODE REVIEW

**Comment by robert3005** [comment]
💯

**Comment by ash211** [comment]
Since this was a hairy one, can we put in a test with this PR?

**Comment by schlosna** [comment]
👍  once we add a couple tests

**Comment by ash211** [comment]
@pwoody did you push this upstream too?  Does it belong added to [apache/spark#15835](https://github.com/apache/spark/pull/15835)

**Comment by pwoody** [comment]
Yes, but I'd like to address the memory usage problem before updating that PR again.

**Pull request merged**
