### PR TITLE
Preparing 1.3.1-palantir2 release

### PR DESCRIPTION
**Pull request by mingyukim**
Preparing 1.3.1-palantir2 release

### CODE REVIEW

**Comment by mingyukim** [comment]
@punya, @mccheah for SA.

**Comment by punya** [comment]
:+1:

**Comment by mccheah** [comment]
Ship it!

              |    |    |
             )_)  )_)  )_)
            )___))___))___)\
           )____)____)_____)\\
         _____|____|____|____\\\__
---------\                   /---------
  ^^^^^ ^^^^^^^^^^^^^^^^^^^^^
    ^^^^      ^^^^     ^^^    ^^
         ^^^^      ^^^

**Comment by punya** [comment]
@mccheah you should use triple-backticks before and after ASCII boats.

```
                              __    __    __
                             |==|  |==|  |==|
                           __|__|__|__|__|__|_
                        __|___________________|___
                     __|__[]__[]__[]__[]__[]__[]__|___
                    |............................o.../
                    \.............................../
               hjw_,~')_,~')_,~')_,~')_,~')_,~')_,~')/,~')_
```

**Comment by mingyukim** [comment]
Forgot to merge this in. Merging

**Pull request merged**
