### PR TITLE
[NOSQUASH] Resync Apache

### PR DESCRIPTION
**Pull request by onursatici**
Notable commits:
- https://github.com/palantir/spark/pull/282/commits/0e9a750a8d389b3a17834584d31c204c77c6970d [SPARK-20643][CORE] Add listener implementation to collect app state.
- https://github.com/palantir/spark/pull/282/commits/8e9863531bebbd4d83eafcbc2b359b8bd0ac5734 [SPARK-22366] Support ignoring missing files
-  https://github.com/palantir/spark/pull/282/commits/01f6ba0e7a12ef818d56e7d5b1bd889b79f2b57c [SPARK-22181][SQL] Adds ReplaceExceptWithFilter rule
- https://github.com/palantir/spark/pull/282/commits/7986cc09b1b2100fc061d0aea8aa2e1e1b162c75 [SPARK-11334][CORE] Fix bug in Executor allocation manager
- https://github.com/palantir/spark/pull/282/commits/444bce1c98c45147fe63e2132e9743a0c5e49598 [SPARK-19112][CORE] Support for ZStandard codec
- https://github.com/palantir/spark/pull/282/commits/1ffe03d9e87fb784cc8a0bae232c81c7b14deac9 [SPARK-22190][CORE] Add Spark executor task metrics to Dropwizard
- https://github.com/palantir/spark/pull/282/commits/6c6626614e59b2e8d66ca853a74638d3d6267d73 [SPARK-22211][SQL] Remove incorrect FOJ limit pushdown

### CODE REVIEW

**Comment by ash211** [comment]
@onursatici was this a clean merge?  Usually git makes messages that look like this:

```
89e0406f8f Andrew Ash 2 weeks ago Merge remote-tracking branch 'origin/master' into aash/resync-apache
```

So not sure if you used a different process for this merge since the message is isn't the auto-generated one

**Comment by onursatici** [comment]
@ash211 we had two conflicts, The move away from sysProps to sparkConf in SparkSubmit conflicted with the k8s bits, and the pom.xml conflicted on antlr. looking into it

**Comment by ash211** [comment]
Ah, a technique I picked up from @mccheah that I've found useful is to make the merge commit with the conflicts unresolved (the `<<<<<<` etc still present), then a subsequent commit to fix the conflict.

This way it's easy to review how the conflicts were resolved, whereas it's impossible to determine that right now when the merge and the conflict resolution are in the same commit.

**Comment by onursatici** [comment]
Yeah makes sense, will do that and rebase

**Pull request merged**
