### PR TITLE
bump hadoop to 2.9.2-palantir.9

### PR DESCRIPTION
**Pull request by sjrand**
Very small diff: https://github.com/palantir/hadoop/compare/2.9.2-palantir.8...2.9.2-palantir.9.

Should be no risk, but helps with some memory issues as described in https://issues.apache.org/jira/browse/HADOOP-16278.

### CODE REVIEW

**Comment by mccheah** [comment]
@yifeih for SA. I'm +1 on this.

**Comment by yifeih** [comment]
I'm curious, there was a revert here: https://github.com/palantir/hadoop/compare/2.9.2-palantir.8...2.9.2-palantir.9#diff-9c6c21166911ba5966c34ca6eeb50b69R5. does that mean there's something wrong with the previous release of Spark, since it was based on 2.9.2-palantir.8? Other than that, this looks good to me!

**Comment by sjrand** [comment]
The revert was of a commit that I added after the `2.9.2-palantir.8` release. It was meant to be an extra addition to `2.9.2-palantir.9`, but then I realized that this didn't make sense.

So nothing to be concerned about re: the previous Spark release.

**Comment by yifeih** [comment]
Ah ok I see, great. Also, before we merge, are there any potential risks in any of the backports that you know of?

**Comment by sjrand** [comment]
In `2.9.2-palantir.9`, we just comment out a metric, so should be as low risk as it gets.

**Comment by yifeih** [comment]
Ah right sorry. I got confused because of the changelog list

**Pull request merged**
