### PR TITLE
Bump jetty version

### PR DESCRIPTION
**Pull request by bkrieger**
## What changes were proposed in this pull request?

Bumping the verson of jetty to 9.4.8.v20171121.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/spark](https://github.com/palantir/spark), @bkrieger! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by bkrieger** [comment]
@robert3005 for review.

**Comment by bkrieger** [comment]
@robert3005 looks like this doesn't trigger a Circle build?

**Comment by ash211** [comment]
@bkrieger we don't build forks (to avoid leaking the publish creds).  Can you please 1) join the public Palantir GitHub group and then 2) send this PR from a branch in this repo, rather than a separate repo?

**Comment by bkrieger** [comment]
Closing in favor of https://github.com/palantir/spark/pull/296.

**Pull request closed without merging**
