### PR TITLE
hadoop 2.9.1 ... maybe this time it will work out okay

### PR DESCRIPTION
**Pull request by sjrand**
@robert3005 I'll also make a 3.1.1 version, but here's this in the meantime

Fixes https://jira.apache.org/jira/browse/SPARK-24493 for us because this Hadoop version includes a backport of https://jira.apache.org/jira/browse/HDFS-12670.

### CODE REVIEW

**Comment by sjrand** [comment]
Build failure seems unrelated to the PR as far as I can tell -- getting `java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded`, which sounds like we need bigger containers or less parallelism?

**Comment by robert3005** [comment]
@sjrand retrigger

**Comment by sjrand** [comment]
@robert3005 can I have write perms for this repo? Circle claims that I need that to re-run builds

**Comment by robert3005** [comment]
You do have write access - you pushed to a branch on this repo. circle sometimes gets confused, log out and log in again

**Comment by sjrand** [comment]
Gah, yeah, that was silly. Thanks for retriggering

**Pull request merged**
