### PR TITLE
Bring in Azure Datalake to Hadoop 2.8+ builds

### PR DESCRIPTION
**Pull request by pwoody**
@robert3005  @ash211 

I actually haven't had to add a dependency here before, so not sure if there is more to be done here. The dist properly brings in the dependency though.

### CODE REVIEW

**Comment by pwoody** [comment]
@sjrand

**Comment by sjrand** [comment]
Worth sending upstream? I'm confused as to why this wasn't part of SPARK-7481

**Comment by robert3005** [comment]
Upstream?

**Comment by pwoody** [comment]
There isn't a profile for hadoop 2.8. I saw that there was opposition in a PR to making one, but I'm not sure how we get the hadoop 2.8 exclusive dependency without makjng another profile.

**Comment by robert3005** [comment]
Eh, alright. Let's not block on upstream picking up new versions.

**Pull request merged**
