### PR TITLE
allow circle to build for remote branches

### PR DESCRIPTION
**Pull request by yifeih**
Testing whether circle CI starts...

### CODE REVIEW

**Comment by yifeih** [comment]
@mccheah @dansanduleac 
Not sure why this one failed https://circleci.com/gh/palantir/spark/11108 (it failed to check out the commit hash) but it's been working ever since...? I also couldn't reproduce that error because a rerun of that build worked just fine. 

I could keep pushing changes to trigger more builds if that helps?

**Comment by robert3005** [comment]
Build forks is a setting in circle - you need to change it there?

**Comment by yifeih** [comment]
Do you mean "Build forked pull requests" on this page? https://circleci.com/gh/palantir/spark/edit#advanced-settings. That was already on before I started this PR

**Comment by robert3005** [comment]
Yes, that. I thought that would be enough

**Comment by yifeih** [comment]
Yea but it was consistently failing to fetch remote branches... i think it's because we overrode the circle checkout code. the regular code looks different. it doesn't have the branch environment variable (see "checkout" step here: https://circleci.com/gh/palantir/conjure-java-runtime/3543?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by yifeih** [comment]
But this seems to work now. Let me push a few more changes or start a new PR just to confirm

**Comment by yifeih** [comment]
checkout seems to be working on new PRs, not sure what caused the previous flake: https://github.com/palantir/spark/pull/494

**Comment by mccheah** [comment]
> Think this is fine - @robert3005 would there be any reason not to introduce this anyway? Seems like it fixes some fork-based PRs.

Whoops, this broke the build so...

**Pull request merged**
