### PR TITLE
Bump codahale metrics

### PR DESCRIPTION
**Pull request by bkrieger**
Bumping the version of codahale metrics from 3.2.5 to 4.0.2

### CODE REVIEW

**Comment by robert3005** [comment]
We can't do this outside of major version since this is mostly used as a library. All the other bumps I have done in this repo are only for minor versions. As you can see from circle logs it's not as trivial as just bumping the version

**Comment by bkrieger** [comment]
Ok, closing.

**Comment by schlosna** [comment]
@bkrieger curious, was there something specific you were looking to use in metrics 4.0? Agree with Rob that this would possibly cause downstream chaos, so probably want to think through consequences & tradeoffs before upgrading in libs.

From https://github.com/dropwizard/metrics/releases main changes look like:

* Compiled and targeted JDK8
* Support for running under JDK9 #1236
* Move JMX reporting to the metrics-jmx module
* Add Bill of Materials for Metrics #1239
* Used Java 8 Time API for data formatting
* Removed unnecessary reflection hacks for HealthCheckRegistry
* Removed internal LongAdder
* Removed internal ThreadLocalRandom
* Optimized generating random numbers
* Timer.Context now implements AutoCloseable
* Upgrade Jetty integration to Jetty 9.4
* Support tracking Jersey filters in Jersey resources (#1118, #1193)
* Add ResponseMetered annotation for Jersey resources (#1186)
* Add a method for timing non-throwing functions. (#1224)
* Unnecessary clear operation for ChunkedAssociativeArray (#1211)
* Add some common metric filters (#1210)
* Add possibility to subclass Timer.Context (#1226)
* Jetty9: unhandled response should be counted as 404 and not 200 (#1232)

**Comment by bkrieger** [comment]
There's nothing specific I want; I have another library that depends on 4.x and I wanted to use that library and Spark in the same application.

**Pull request closed without merging**
