### PR TITLE
[WIP] Resync kube upstream

### PR DESCRIPTION
**Pull request by ash211**
NOSQUASH -- merge when merging this, don't squash and merge

Planning to add another commit or two to this before merging

### CODE REVIEW

**Comment by robert3005** [comment]
please fix #191 first

**Comment by ash211** [comment]
@mccheah I'd like to have this PR pull in only stuff that's merged from upstream, and do the SBT fixes in a separate PR.  Just a matter of rearranging commits later

**Comment by mccheah** [comment]
I'll rebase to remove build-related commits later.

**Comment by robert3005** [comment]
We should add spark-kubernetes to dists boms

**Comment by mccheah** [comment]
this wasn't meant to be merged

**Comment by ash211** [comment]
Wasn't merged -- I'll open a new PR when the SBT fix lands

**Comment by ash211** [comment]
Replaced by https://github.com/palantir/spark/pull/208

**Pull request closed without merging**
