### PR TITLE
Sr/new master

### PR DESCRIPTION
**Pull request by sjrand**
Conflicts resolved in last commit.

### CODE REVIEW

**Comment by sjrand** [comment]
So after https://github.com/apache/spark/pull/22266, we need `flake8` in the container that runs the `run-style-tests` job, which it looks like comes from the `palantirtechnologies/circle-spark-base` image.

**Comment by sjrand** [comment]
Also, in our `Dockerfile` for R, we do ` devtools::install_github('r-lib/testthat@v2.0.0', lib='/usr/local/lib/R/site-library')`, which I think is what's breaking the R tests. I think we need version 1.0.2, which is what's in the `appveyor.yml` file. See https://jira.apache.org/jira/browse/SPARK-22817.

**Comment by robert3005** [comment]
@sjrand Dockerfiles for build containers are in this repo. Ping me so I can get you the creds to publish them to dockerhub. I think they changed the version on master so you need to make sure it's updated everywhere

**Comment by sjrand** [comment]
Finally have everything green except for the scala tests. I suspect that the failures in `AppStatusListenerSuite` and the ones in `HistoryServerSuite` are related, since they both hit the same code path that interacts w/LevelDB.

**Comment by sjrand** [comment]
Woo, green! Thanks Rob for pointing me to the jackson fix. For those reviewing, the conflict resolution PR is https://github.com/palantir/spark/pull/414/commits/20c66ef7569ea151ea9b3a0e983897f86b960d9d. There's also a very small second conflict resolution PR in https://github.com/palantir/spark/pull/414/commits/14ff6fd46d5c3b2eddb0f36daaf23c9e2f076630 since I merged in master again after resolving conflicts the first time.

**Pull request merged**
