### PR TITLE
Fix createFilter for NOT queries

### PR DESCRIPTION
**Pull request by pwoody**
@robert3005 @schlosna

### CODE REVIEW

**Comment by pwoody** [comment]
@lynchmattj

**Comment by robert3005** [comment]
This should be sent upstream right? This looks like a generic issue and we just exposed it via better filter pushdown

**Comment by pwoody** [comment]
Indeed will open there as well

**Comment by schlosna** [comment]
@pwoody 👍 LGTM

Assuming we were hitting the https://github.com/Parquet/parquet-mr/blob/master/parquet-hadoop/src/main/java/parquet/filter2/statisticslevel/StatisticsFilter.java#L264 which seems to have been issue upstream since https://github.com/apache/spark/pull/6090

**Pull request merged**
