### PR TITLE
Make 2.4.0-palantir.7 in-process launching safe

### PR DESCRIPTION
**Pull request by yifeih**

### CODE REVIEW

**Comment by yifeih** [comment]
hmm i'm currently running into a problem with sparkR tests...? retriggering/digging into this:
```
Warning message:
package ‘SparkR’ was built under R version 3.4.4 
Spark package found in SPARK_HOME: /home/ubuntu/spark
══ testthat results  ═══════════════════════════════════════════════════════════
OK: 13 SKIPPED: 0 FAILED: 0
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'run_tests' not found
Calls: ::: -> get
Execution halted
```

**Comment by robert3005** [comment]
You won't get circle 1 build passing - some of the beta features we have been using have been removed.

**Comment by robert3005** [comment]
You will most likely need to patch pr with new circle config

**Comment by yifeih** [comment]
talked to @mccheah, moving the circle-2 stuff into a separate PR https://github.com/palantir/spark/pull/382

**Comment by yifeih** [comment]
@mccheah @robert3005 adding the caches back in seem to have screwed up the python tests, so i took them out. since we won't be making many changes to this branch anyway, i think that's probably fine. can you take a look at the rest of the PR? thanks!

**Pull request merged**
