### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by mccheah**
Particularly to pick up https://github.com/apache/spark/pull/22112

### CODE REVIEW

**Comment by mccheah** [comment]
@robert3005 merge conflict resolution is in the last commit.

**Comment by mccheah** [comment]
Is it fine to just merge if we hit the Python test flake?

**Comment by robert3005** [comment]
We should ignore the test

**Comment by robert3005** [comment]
Those streaming tests are really bad

**Comment by mccheah** [comment]
Ok, I'm going to merge this then. Thanks!

**Comment by robert3005** [comment]
@mccheah DO NOT merge red prs. When I said ignore - you should ignore them in code so they don't run and not rely on them being flakes. Please fix your pr

**Pull request merged**
