### PR TITLE
k8s module

### PR DESCRIPTION
**Pull request by robert3005**
@ash211 @mccheah that's what I meant

### CODE REVIEW

**Comment by mccheah** [comment]
It looks like adding the Kubernetes profile messes up all the unrelated tests, like YARN and hive. What would be the cause of this?

**Comment by ash211** [comment]
Most likely some sort of dependency resolution issue -- maybe the resolved dep trees aren't the same between Maven and SBT?

**Comment by mccheah** [comment]
Looks like we have a lot of instances of this:

`2017-05-22 16:11:22.907 - stderr> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.7.7`

Seems that Jackson is being resolved differently in SBT.

**Comment by ash211** [comment]
SBT doesn't know about version recommendations, so @robert3005 suggests that we need to find what dep pulls in jackson and exclude jackson-databind and jackson-core from that dep.

Hypothesis: it's the fabric8 client that brings in jackson

**Comment by robert3005** [comment]
fixed in #192

**Comment by ash211** [comment]
(though doing the SBT build fix separately from the kube resync PR)

**Pull request closed without merging**
