### PR TITLE
Apply patches for SPARK-24531 to fix tests

### PR DESCRIPTION
**Pull request by mccheah**

### CODE REVIEW

**Comment by mccheah** [comment]
@yifeih @robert3005 for SA. Merging when build is green.

**Comment by robert3005** [comment]
Can we just merge upstream instead?

**Comment by mccheah** [comment]
It is merged upstream, this is just cherry picking,.

**Comment by robert3005** [comment]
Saying that we should merge upstream. But don’t block really. Just don’t
cherry pick ad infinitum

**Pull request merged**
