### PR TITLE
Preparing 1.3.0-palantir2 release

### PR DESCRIPTION
**Pull request by mingyukim**
- Backporting SPARK-6905
- Preparing 1.3.0-palantir2 release

### CODE REVIEW

**Comment by mingyukim** [comment]
@mccheah, can you take a look?

**Comment by mccheah** [comment]
Might as well put in a description, as that description is what is used on the merge commit when I close the PR I think.

**Comment by mccheah** [comment]
Also make the title informative =)

**Comment by mingyukim** [comment]
Done :)

**Comment by punya** [comment]
Did you guys end up not using this PR? I saw the release announcement go out today, but this isn't merged in.

**Comment by mingyukim** [comment]
I keep forgetting to update this. The release is based on this PR. I'll push this in and tag the release.

**Pull request merged**
