### PR TITLE
More upstream merges

### PR DESCRIPTION
**Pull request by robert3005**

### CODE REVIEW

**Comment by robert3005** [comment]
@mccheah any pointers how to refactor local files for new structure?

**Comment by mccheah** [comment]
Yup, anticipated this and plan to follow up. I'll get to it in the next 24-48 hrs.

**Comment by mccheah** [comment]
@robert3005 https://github.com/palantir/spark/pull/358/commits/9783aa765692bfe892de33bae169c2891aeef23a has the migration patch.

**Comment by mccheah** [comment]
@robert3005 ported https://github.com/palantir/spark/pull/358/commits/dc0b46618b49bdf7e989d695d21eb7f67f891410 for file sanitization - found this was a problem in internal testing.

**Comment by robert3005** [comment]
@mccheah it wasn't quite right - you can't call setjars even with empty array

**Pull request merged**
