### PR TITLE
Revert soft dynamic allocation for SPARK-25299.

### PR DESCRIPTION
**Pull request by mccheah**
When working on SPARK-25299 specifically, we want to work off of the master branch's version of various parts of the code that soft dynamic allocation changed.

Due to the way the code diverged, and due to the way conflict resolution was performed when merging from upstream, simply reverting the commits that introduced the feature was not trivial. We instead followed a more manual approach:

1. git checkout the upstream master version of `MapOutputTracker`
2. Find all compilation errors in dependent classes
3. git checkout the upstream master version of all broken classes
4. Repeat 2-3 until no compilation errors are left

### CODE REVIEW

**Comment by mccheah** [comment]
@rynorris we could use some help in figuring out if we reverted all the right things here.

**Comment by lwwmanning** [comment]
I'd much rather contribute the dynamic allocation stuff upstream, since we've tested it and it works as expected (albeit still needs work to be properly supported in https://github.com/palantir/k8s-spark-scheduler )

**Comment by yifeih** [comment]
@lwwmanning we're not reverting it on master, just the feature branch on which we're developing the ESS changes. we want this so our perf and unit tests accurately reflect what's happening upstream

**Comment by lwwmanning** [comment]
Ohhh, I see. Well, was a good impetus for me to finally create https://github.com/apache/spark/pull/24083

**Comment by yifeih** [comment]
compared this with Will's upstream PR and apache/master. for the most part, this looks good to me, except tests are failing. i think you've checked the files out from apache/master, not palantir/master, so might be worth merging from upstream first so we're not taking half of the changes in certain diffs in this PR. or not if there are a lot of merge conflicts, but tests should at least pass.

also, as for the k8s soft dynamic allocation upstream PR, agreed that we should upstream the changes, so we'll take a look at that PR. however, i don't think we should block this work on that, so let's merge this into the feature branch for now and then undo this when the upstream PR merges

**Comment by lwwmanning** [comment]
Cool, yeah, don't want to block experimentation. However, I would want to block merging the feature branch into palantir/master on effectively reverting this PR.

**Comment by mccheah** [comment]
When we propose the experimental work against upstream we're going to cherry-pick our patches to make the diff there. Then when we merge into palantir/master we can resolve the merge conflicts and deal with our stuff then. Or, if https://github.com/apache/spark/pull/24083 merges we'll just take that in the feature branch anyways.

**Comment by mccheah** [comment]
The only place I didn't check out master in was in `SparkContext` actually - just fixed the compilation errors manually there.

**Comment by mccheah** [comment]
I'll try also taking a merge from upstream - there's a lot of conflicts but I think they're routine that we fix all the time for the most part.

**Comment by mccheah** [comment]
@ifilonenko

**Comment by rynorris** [comment]
@mccheah looks to me like you've hit all the parts of the core code (that I can recall).

You haven't reverted the changes to the k8s pieces made in https://github.com/palantir/spark/pull/427 though, mainly `ExecutorPodsAllocator`.  Are you intending to keep those changes?

**Comment by mccheah** [comment]
I took a closer look at the diff. I believe everything is only with regards to `SafeLogging`. Might as well keep those.

**Comment by mccheah** [comment]
Ok, the build is finally passing. Not sure what was causing the problems.

@yifeih can we get a final sign off to merge here?

**Comment by mccheah** [comment]
I'm going to revert the changes I made to circleci YML that forced the caches to invalidate. That might make the build fail again if it restores bad caches, but we'll declare that the build was passing at one point and hopefully the build on the feature branch should pass regardless.

**Comment by mccheah** [comment]
Ok, merging now!

**Pull request merged**
