### PR TITLE
Downgrade hadoop to 2.8.2-palantir.2

### PR DESCRIPTION
**Pull request by rahij**
@ash211 @sjrand 

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

Faith

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by ash211** [comment]
@rahij can you please send PRs from this repo instead of a fork in the future?  That way circle will run integration tests.

**Comment by rahij** [comment]
I somehow couldn't push directly, can you give me access? (Also you can enable running integration tests on forks as well on circle).

**Comment by ash211** [comment]
you're enabled

**Comment by ash211** [comment]
Yep working on fixing that library independently, but the upside of merging now is that we have a version to land on for correctness issue at https://github.com/palantir/spark/issues/286

**Pull request merged**
