### PR TITLE
[SPARK-7481] Add cloud dependencies

### LINKED ISSUE #135: Consider merging fix for SPARK-7481
https://github.com/apache/spark/pull/12004

### PR DESCRIPTION
**Pull request by robert3005**
Adds cloud dependencies. Adjusted from https://github.com/apache/spark/pull/12004

cc @ash211 @sjrand 

fixes #135

### CODE REVIEW

**Comment by sjrand** [comment]
Sweet. Would love for this to be a thing.

Does it still work for 2.8.0/palantir-hadoop? I think the original PR was written before 2.8.0 came out.

**Comment by robert3005** [comment]
I think I did the correct thing but need to verify 2.8.0 dependencies to be sure

**Comment by ash211** [comment]
Merging for internal testing

**Comment by ash211** [comment]
Confirmed working as expected in internal testing

**Pull request merged**
