### PR TITLE
Pw/parquet pruning

### PR DESCRIPTION
**Pull request by pwoody**
@robert3005 @schlosna

### CODE REVIEW

**Comment by pwoody** [comment]
This passes hive and sql tests locally

**Comment by schlosna** [comment]
@pwoody just to confirm, this is essentially https://github.com/apache/spark/pull/15835 from upstream + revert & fixing up of Duffy's changes, right?

**Comment by schlosna** [comment]
👍  LGTM

**Comment by pwoody** [comment]
Yep, that is the case @schlosna . Minor tweak since we are ahead on parquet version as well

**Pull request merged**
