### PR TITLE
Preparing 1.3.1-palantir1 release

### PR DESCRIPTION
**Pull request by mccheah**
Contains all patches in 1.3.0-palantir2 that are not already in vanilla 1.3.1, and also a Parquet output committing fix for S3.

### CODE REVIEW

**Comment by mccheah** [comment]
cc @punya and @ash211 for approval!

**Comment by mccheah** [comment]
Actually let's wait a little longer to see if anyone else wants things in this patch release.

**Comment by punya** [comment]
:+1:

**Comment by mccheah** [comment]
Yeah let's merge it!

**Comment by punya** [comment]
Where did the artifacts for this end up?

**Comment by mccheah** [comment]
Still working on that.

**Pull request merged**
