### PR TITLE
Resync from kube upstream

### PR DESCRIPTION
**Pull request by ash211**
Two commits had merge conflicts:

- `Python Bindings for launching PySpark Jobs from the JVM`
- `Submission client redesign to use a step-based builder pattern`

### CODE REVIEW

**Comment by ash211** [comment]
@mccheah looks like we don't pass scalastyle:

```
[INFO] --- scala-maven-plugin:3.2.2:doc-jar (attach-scaladocs) @ spark-kubernetes_2.11 ---
/home/ubuntu/spark/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/DriverKubernetesCredentialsStep.scala:211: warning: implicit conversion method augmentSparkConf should be enabled
by making the implicit value scala.language.implicitConversions visible.
This can be achieved by adding the import clause 'import scala.language.implicitConversions'
or by setting the compiler option -language:implicitConversions.
See the Scaladoc for value scala.language.implicitConversions for a discussion
why the feature should be explicitly enabled.
  private implicit def augmentSparkConf(sparkConf: SparkConf): OptionSettableSparkConf = {
                       ^
model contains 30 documentable templates
one warning found
```

**Comment by mccheah** [comment]
Requires https://github.com/apache-spark-on-k8s/spark/pull/374

**Comment by ash211** [comment]
@mccheah now seeing this:

```
error file=/home/ubuntu/spark/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala message=import.ordering.wrongOrderInGroup.message line=39 column=0^M
Saving to outputFile=/home/ubuntu/spark/resource-managers/kubernetes/core/target/scalastyle-output.xml^M
Processed 52 file(s)^M
```

**Comment by ash211** [comment]
More locally (on branch-2.1-kubernetes):

```
[error] /Volumes/git/spark/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/InitContainerResourceStagingServerSecretPluginSuite.scala:20:0: import.ordering.wrongOrderInGroup.message
[error] /Volumes/git/spark/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/InitContainerResourceStagingServerSecretPluginSuite.scala:21:0: import.ordering.missingEmptyLine.message
[error] /Volumes/git/spark/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/InitContainerResourceStagingServerSecretPluginSuite.scala:23:0: import.ordering.wrongGroup.message
[error] /Volumes/git/spark/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/SparkPodInitContainerBootstrapSuite.scala:20:0: import.ordering.wrongOrderInGroup.message
[error] /Volumes/git/spark/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/SparkPodInitContainerBootstrapSuite.scala:21:0: import.ordering.missingEmptyLine.message
[error] /Volumes/git/spark/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/SparkPodInitContainerBootstrapSuite.scala:23:0: import.ordering.wrongGroup.message
```

**Comment by ash211** [comment]
Oops squashed instead of merged -- will just have to remember that next we resync from upstream

**Pull request merged**
