### PR TITLE
Take authentication + SSL Changes from Kubernetes upstream

### LINKED ISSUE #133: Authentication + SSL Changes from Kubernetes Upstream
Pull these from upstream once they merge:

https://github.com/apache-spark-on-k8s/spark/pull/180
https://github.com/apache-spark-on-k8s/spark/pull/173
https://github.com/apache-spark-on-k8s/spark/pull/186

### PR DESCRIPTION
**Pull request by mccheah**
Closes #133

### CODE REVIEW

**Comment by mccheah** [comment]
Still missing 2 of the 3 PRs that we need.

**Comment by mccheah** [comment]
I cherry-picked https://github.com/apache-spark-on-k8s/spark/pull/192, also taking https://github.com/apache-spark-on-k8s/spark/pull/176 to avoid merge conflicts. Still need https://github.com/apache-spark-on-k8s/spark/pull/173

**Comment by ash211** [comment]
Wrong branch -- we're releasing k8s stuff off of palantir:master now.  I'll set up a new PR that resyncs from k8s upstream

**Comment by ash211** [comment]
Replaced with https://github.com/palantir/spark/pull/137

**Pull request closed without merging**
